### ISSUE TITLE
wombag: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by hefistion** [karthink/wombag#1]
Hi, thank you very much for your work, I have an error `wombag: Wrong type argument: stringp, nil` when I try to run wombag.

I have cloned the package and installed it via package-install-file

my configuration file

```
    (use-package wombag
      :config
       (setq wombag-host "https://my-server" ;where you access Wallabag
             wombag-username "my-user"
             wombag-password "passworrd user"
             wombag-client-id "xxxxxxxxxxxxxxxxx"
             wombag-client-secret "xxxxxxxxxxxxxxx"))
```

Emacs version:
```
GNU Emacs 29.1
Copyright (C) 2023 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
```

Wallabag version_ 2.6.7

Compile log

```
Leaving directory ‘/home/carlos/.emacs.d/elpa/emacsql-20230417.1448’

Compiling file /home/carlos/.emacs.d/elpa/emacsql-20230417.1448/emacsql-compiler.el at Thu Dec 21 19:33:17 2023
Entering directory ‘/home/carlos/.emacs.d/elpa/emacsql-20230417.1448/’

Compiling file /home/carlos/.emacs.d/elpa/emacsql-20230417.1448/emacsql-mysql.el at Thu Dec 21 19:33:17 2023

Compiling file /home/carlos/.emacs.d/elpa/emacsql-20230417.1448/emacsql-pg.el at Thu Dec 21 19:33:17 2023

Compiling file /home/carlos/.emacs.d/elpa/emacsql-20230417.1448/emacsql-psql.el at Thu Dec 21 19:33:17 2023

Compiling file /home/carlos/.emacs.d/elpa/emacsql-20230417.1448/emacsql-sqlite-builtin.el at Thu Dec 21 19:33:17 2023

Compiling file /home/carlos/.emacs.d/elpa/emacsql-20230417.1448/emacsql-sqlite-common.el at Thu Dec 21 19:33:17 2023

Compiling file /home/carlos/.emacs.d/elpa/emacsql-20230417.1448/emacsql-sqlite-module.el at Thu Dec 21 19:33:17 2023

Compiling file /home/carlos/.emacs.d/elpa/emacsql-20230417.1448/emacsql-sqlite.el at Thu Dec 21 19:33:17 2023

Compiling file /home/carlos/.emacs.d/elpa/emacsql-20230417.1448/emacsql.el at Thu Dec 21 19:33:17 2023

Compiling internal form(s) at Thu Dec 21 19:33:18 2023
Leaving directory ‘/home/carlos/.emacs.d/elpa/wombag-0.1.0’

Compiling file /home/carlos/.emacs.d/elpa/wombag-0.1.0/wombag-db.el at Thu Dec 21 19:33:18 2023
Entering directory ‘/home/carlos/.emacs.d/elpa/wombag-0.1.0/’

In end of data:
wombag-db.el:37:16: Warning: the function ‘emacsql-sqlite-builtin’ is not
    known to be defined.

Compiling file /home/carlos/.emacs.d/elpa/wombag-0.1.0/wombag-heading.el at Thu Dec 21 19:33:18 2023

Compiling file /home/carlos/.emacs.d/elpa/wombag-0.1.0/wombag-options.el at Thu Dec 21 19:33:18 2023

Compiling file /home/carlos/.emacs.d/elpa/wombag-0.1.0/wombag-search.el at Thu Dec 21 19:33:18 2023

In wombag-search-format-entry:
wombag-search.el:397:11: Warning: Unused lexical variable `authors'

Compiling file /home/carlos/.emacs.d/elpa/wombag-0.1.0/wombag-show.el at Thu Dec 21 19:33:18 2023

In wombag-show-entry:
wombag-show.el:137:40: Warning: ‘button-buttonize’ is an obsolete function (as
    of 29.1); use ‘buttonize’ instead.

Compiling file /home/carlos/.emacs.d/elpa/wombag-0.1.0/wombag.el at Thu Dec 21 19:33:18 2023

```

Buffer warnings

```
 ⛔ Warning (comp): wombag-db.el:37:16: Warning: the function ‘emacsql-sqlite-builtin’ is not known to be defined.
 ⛔ Warning (comp): wombag-show.el:137:40: Warning: ‘button-buttonize’ is an obsolete function (as of 29.1); use ‘buttonize’ instead.
 ⛔ Warning (comp): wombag-search.el:397:11: Warning: Unused lexical variable `authors'
```

thank you very much

**Comment by karthink** [comment]
It looks like it installed correctly.   Could you run `M-x toggle-debug-on-error`, retry and paste the backtrace here?

**Comment by hefistion** [comment]
Thank you for your quick response

M-x toggle-debug-on-error

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  wombag-db-ensure()
  wombag()
  funcall-interactively(wombag)
  command-execute(wombag record)
  execute-extended-command(nil "wombag" "wom")
  funcall-interactively(execute-extended-command nil "wombag" "wom")
  command-execute(execute-extended-command)
```

The process for the installation was
`git clone https://github.com/karthink/wombag.git /tmp/wombag`

`M-x package-install-file RETURN /tmp/wombag/`

Is this correct?

Thank you very much

**Comment by karthink** [comment]
Yes, the installation method looks correct.

- That backtrace narrows it down, thank you.  Could you check if the variable `wombag-db-file` is bound to anything?
- Ditto for the variable `wombag-dir`.

**Comment by hefistion** [comment]
**wombag-dir**  


```
`wombag-dir is a variable defined in ‘wombag-options.el’.

Its value is "~/.emacs.d/wombag"

Wombag data directory.
```

**wombag-db-file**

```
`wombag-db-file is a variable defined in ‘wombag-options.el’.

Its value is "Sqlite database used to store Wombag data."

~/.emacs.d/wombag/wombag.sqlite

  You can customize this variable.
```

```
~ > ls -lh ~/.emacs.d/wombag

total 0

```

**Comment by karthink** [comment]
```
`wombag-db-file is a variable defined in ‘wombag-options.el’.

Its value is "Sqlite database used to store Wombag data."

~/.emacs.d/wombag/wombag.sqlite

  You can customize this variable.
  ```

Just making sure -- did you exchange the value of this variable and its description?

**Comment by karthink** [comment]
I'm unable to determine what is causing the error in `wombag-db-ensure`.  Could you try edebug on this function?

1. `M-x find-function wombag-db-ensure`
2. `C-u C-M-x`
3. Run `M-x wombag`.

You can then step through this function with `n` and `p`, and hopefully figure out which line the error is on.

**Comment by hefistion** [comment]
> ```
> `wombag-db-file is a variable defined in ‘wombag-options.el’.
> 
> Its value is "Sqlite database used to store Wombag data."
> 
> ~/.emacs.d/wombag/wombag.sqlite
> 
>   You can customize this variable.
> ```
> 
> Just making sure -- did you exchange the value of this variable and its description?

No, I did the installation as I wrote above.

I cloned the repository and installed the package, and modified my configuration file.

**Comment by hefistion** [comment]
```
(defun w-db-ensure ()
  ";TODO:"
  (unless (and w-db-connection **Result  is nil**  (emacsql-live-p w-db-connection)) **Result: is nil**
    (let ((dir (file-name-directory w-db-file **Result: "Sqlite database used to store Wombag data."**) **Result: is nil** ))
      (or (file-directory-p dir Result: nil) **Wrong type argument: stringp, nil** (make-directory dir)))
    (setq w-db-connection (funcall w-db-open-func w-db-file))
```

It is in these functions where it fails

**Comment by karthink** [comment]
Should be fixed, please update and check.

> No, I did the installation as I wrote above.
> 
> I cloned the repository and installed the package, and modified my configuration file.

Here's what I meant: If you look carefully at this description,

```
`wombag-db-file is a variable defined in ‘wombag-options.el’.

Its value is "Sqlite database used to store Wombag data."

~/.emacs.d/wombag/wombag.sqlite

  You can customize this variable.
```

You can see that what should be its documentation (`"Sqlite database used to store Wombag data."`) is reported as its value, and what should be its value (`~/.emacs.d/wombag/wombag.sqlite`) is reported as its documentation.  Turns out there was a typo in the code and these two were switched where this variable is defined.  I fixed it now, but there might be other errors so please let me know.

**Comment by hefistion** [comment]
> Should be fixed, please update and check.

Now it works, thank you very much, 

I really like the idea, I will keep testing.

Again, thank you very much for your work

**Comment by karthink** [comment]
Did it download your Wallabag articles correctly, and does search work as advertised?  

(This package is new has not been tested by anyone except myself with my Wallabag instance.)

**Comment by hefistion** [comment]
> Did it download your Wallabag articles correctly, and does search work as advertised?
> 

No, in my instance I have 89 articles and only 59 have been downloaded.

![Captura desde 2023-12-22 21-54-39](https://github.com/karthink/wombag/assets/6677900/a4afdceb-fba1-4708-abfd-4a85f2b8ed76)


![Captura desde 2023-12-22 21-52-37](https://github.com/karthink/wombag/assets/6677900/71f19780-bf8a-4292-b389-32e06202498e)

one issue, I have 4 archived articles, if I apply the filter to see only the archived articles (`&&`) nothing happens. They appear in the list of all articles.


![Captura desde 2023-12-22 21-56-05](https://github.com/karthink/wombag/assets/6677900/95b19ab2-2a07-4f96-a5bf-e676c182acb0)

another issue, to search by tags it should be `+tag` but for it to work it works only with `tag`. also there are only 4 articles tagged as emacs when in reality there are more.

![Captura desde 2023-12-22 21-57-31](https://github.com/karthink/wombag/assets/6677900/1f4f0737-48e2-4952-be3c-8ad1e3c0c92b)

![Captura desde 2023-12-22 21-59-12](https://github.com/karthink/wombag/assets/6677900/5e55c4f8-9121-40e3-bc9e-9d14ecf68fa7)



> (This package is new has not been tested by anyone except myself with my Wallabag instance.)

Don't worry, I don't mind doing as many tests as necessary.

**Comment by karthink** [comment]
@hefistion I created #2 to track the sync issue, please take a look when you have time.
